apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"jellyfin","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jellyfin"}},"template":{"metadata":{"labels":{"app":"jellyfin"}},"spec":{"con$
  creationTimestamp: "2026-01-17T12:28:52Z"
  generation: 9
  name: jellyfin
  namespace: default
  resourceVersion: "99391"
  uid: 125db8f0-60a3-455b-9ec3-038f7224c573
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-01-17T12:32:15Z"
      labels:
        app: jellyfin
    spec:
      containers:
      - image: jellyfin/jellyfin:10.8.13-armhf
        imagePullPolicy: Always
        name: jellyfin
        ports:
        - containerPort: 8096
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data/movies
          name: video-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: filebrowser-config-pvc
      - name: video-storage
        persistentVolumeClaim:
          claimName: hdd-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-17T12:45:34Z"
    lastUpdateTime: "2026-01-17T12:45:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-17T12:28:52Z"
    lastUpdateTime: "2026-01-17T12:45:34Z"
    message: ReplicaSet "jellyfin-86b4bb55db" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

