apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: hdd
              mountPath: /usr/share/nginx/html
      volumes:
        - name: hdd
          hostPath:
            path: /home/pi/Home-Lab/web/
            type: Directory
