apiVersion: v1
kind: Service
metadata:
  name: pi-web-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: pi-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
