apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          imagePullPolicy: Always
          args:
            - --root=/srv
            - --port=80
            - --database=/config/database.db
          ports:
            - containerPort: 80
          volumeMounts:
            - name: hdd
              mountPath: /srv        # full HDD content
            - name: fb-config
              mountPath: /config     # persistent database + config
      volumes:
        - name: hdd
          hostPath:
            path: /mnt/data
            type: Directory
        - name: fb-config
          hostPath:
            path: /mnt/data/.filebrowser-config
            type: DirectoryOrCreate
