apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"filebrowser","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"filebrowser"}},"template":{"metadata":{"labels":{"app":"filebrowser"}},"spec":{"containers":[{"args":["--root=/srv","--port=80","--database=/config/database.db"],"image":"filebrowser/filebrowser:latest","name":"filebrowser","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/srv","name":"hdd"},{"mountPath":"/config","name":"fb-config"}]}],"volumes":[{"hostPath":{"path":"/mnt/data","type":"Directory"},"name":"hdd"},{"hostPath":{"path":"/mnt/data/.filebrowser-config","type":"DirectoryOrCreate"},"name":"fb-config"}]}}}}
  creationTimestamp: "2026-01-18T22:41:38Z"
  generation: 7
  name: filebrowser
  namespace: default
  resourceVersion: "69370"
  uid: b005ad73-6e0f-4753-822f-4395b2be5f96
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: filebrowser
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - args:
        - --root=/srv
        - --port=80
        - --database=/config/database.db
        image: filebrowser/filebrowser:latest
        imagePullPolicy: Always
        name: filebrowser
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv
          name: hdd
        - mountPath: /config
          name: fb-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/data
          type: Directory
        name: hdd
      - hostPath:
          path: /mnt/data/.filebrowser-config
          type: DirectoryOrCreate
        name: fb-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-20T22:04:55Z"
    lastUpdateTime: "2026-01-20T22:04:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-18T22:41:38Z"
    lastUpdateTime: "2026-01-20T22:04:55Z"
    message: ReplicaSet "filebrowser-5446d485c4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
