apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"filebrowser-service","namespace":"default"},"spec":{"ports":[{"nodePort":30080,"port":80,"targetPort":80}],"selector":{"app":"filebrowser"},"type":"NodePort"}}
  creationTimestamp: "2026-01-18T21:19:20Z"
  name: filebrowser-service
  namespace: default
  resourceVersion: "10305"
  uid: 63cbeb08-156f-4141-ad9c-476cb675d229
spec:
  clusterIP: 10.43.124.134
  clusterIPs:
  - 10.43.124.134
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: filebrowser
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
