name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Home-Lab to Pi
    runs-on: self-hosted
    environment: pi-prod

    steps:
      - name: Ensure correct repo
        run: |
          cd /home/pi/Home-Lab
          git status

      - name: Pull latest changes
        run: |
          cd /home/pi/Home-Lab
          git pull origin main

      - name: Show deployed commit
        run: |
          cd /home/pi/Home-Lab
          git log -1 --oneline
